export const Icons = {
    RECTANGLE: "/Icons/rectangle.svg",
    US_FLAG: "/Icons/Ic_US_Flag.svg",
    ARRWOCLOCKWISE: "/Icons/ArrowsClockwise.svg",
    LAYER21: "/Icons/layer-2-1.svg",
    LAYER2: "/Icons/layer-2.svg",
    TRANSNSFERINOUT: "/Icons/TransferInOut.svg",
    USER: "/Icons/user.svg",
    AIRTICKET: "/Icons/AirTicket.svg",
    CULRURAL: "/Icons/Cultural.svg",
    ACCOMODATION: "/Icons/accomodations.svg",
    HAPPY: "/Icons/happy.svg",
    ELEMENT1: "/Icons/element-1.svg",
    PHONE: "/Icons/phone.svg",
    BRAZILFLAG: "/Icons/BrazilFlag.svg",
    UAEFLAG: "/Icons/UAEFlag.svg",
    GLOBE: "/Icons/Globe.svg",
    INSTAGRAMLOGO: "/Icons/InstagramLogo.svg",
    TESTMONIALLOGO: "/Icons/TestMonialLogo.svg",
}


export const Images = {
    GROUP5: "/Images/group-5.png",
    HOMEBG: "/Images/HomeBg.png",
    LOGO: "/Images/Logo.png",
    LOGOFOOTER: "/Images/LOGOFOOTER.png",
    GROUP3: "/Images/group-3.png",
    STOPOVER: "/Images/Stopover.png",
    STOPOVER2: "/Images/StopOver2.png",
    STOPOVER3: "/Images/StopOver3.png",
    TESTMONIAL1: "/Images/TestMonial1.png",
    TESTCARD1: "/Images/TESTCARD1.png",
    TESTMONIAL2: "/Images/TestMonial2.png",
    TESTCARD2: "/Images/TESTCARD2.png",
    TESTMONIAL3: "/Images/TestMonial3.png",
    TESTCARD3: "/Images/TESTCARD3.png",
    WHYDOHABACK: "/Images/whydohaback.png",
    FOUNDERIMAGE: "/Images/FounderImage.png",
    CONTACTUS: "/Images/CONTACTUS.png",
    BOOKSTAY: "/Images/BookStay.png",
    FounderLTOP: "/Images/FounderLTOP.png",
    FounderRTOP: "/Images/FounderRTOP.png",
    FounderRBOTTOM: "/Images/FounderRBOTTOM.png",
    FounderLBOTTOM: "/Images/FounderLBOTTOM.png",
    FounderCENTRE: "/Images/FounderCENTRE.png",
}